# Generated by Django 4.1.7 on 2023-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreedomFighters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('DOD', models.DateField()),
                ('POB', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pp')),
                ('biodata', models.TextField()),
            ],
        ),
    ]
