# Generated by Django 4.1.7 on 2023-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freedomfighters',
            name='id',
        ),
        migrations.AlterField(
            model_name='freedomfighters',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
